config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'visitors#index'
  get "servicios", to: "visitors#servicios"
  get "nosotros", to: "visitors#nosotros"
  get "consultar", to: "visitors#consultar"
  post "pages/update"
  get "pages/edit"
  get 'contact', to: 'mensajes#new', as: 'contact'
  post 'contact', to: 'mensajes#create'
  devise_for :users
  resources :users
  namespace :admin do
    root to: 'dashboard#index'
    resources :clientes
    resources :vehiculos
    resources :estados
    resources :pages
    resources :estado_vehiculos
    resources :ejecutivos
  end
end

app/models/adjunto.rb
class Adjunto < ActiveRecord::Base
  belongs_to :estado_vehiculo

  has_attached_file :archivo,
                    :path => ":rails_root/public/adjuntos/:id/:filename",
                    :url  => "/adjuntos/:id/:filename"

  do_not_validate_attachment_file_type :archivo
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/cliente.rb
include ValidatorsHelper

class Cliente < ActiveRecord::Base
  has_many :vehiculos, :dependent => :destroy
  validates_presence_of :identificacion, :nombre_y_apellidos, :tipo_identificacion, :celular, :direccion, :tipo
  validates :correo, presence: true, email: true

  enum tipo: {
           asegurado: 'Asegurado', responsabilidad_civil: 'Responsabilidad Civil', particular: 'Particular'
       }
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nombre,      :validate => true
  attribute :correo,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensaje
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Nuevo Contacto AutoStop",
        :to => "dairon.medina@gmail.org",
        :from => %("#{nombre}" <#{correo}>)
    }
  end
end

app/models/ejecutivo.rb
include ValidatorsHelper

class Ejecutivo < ActiveRecord::Base
  has_many :vehiculos, dependent: :nullify
  validates_presence_of :nombre
  validates :correo, presence: true, email: true
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_many :estado_vehiculos
end

app/models/estado_vehiculo.rb
class EstadoVehiculo < ActiveRecord::Base
  belongs_to :vehiculo
  belongs_to :estado
  has_many :adjuntos, :dependent => :destroy
  validates_presence_of :vehiculo, :estado, :notas,  :fecha_y_hora
end

app/models/mensaje.rb
class Mensaje

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :nombre_y_apellidos, :correo, :asunto, :mensaje

  validates :nombre_y_apellidos,
            presence: true

  validates :correo,
            presence: true
  validates_format_of :correo, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :asunto,
            presence: true

  validates :mensaje,
            presence: true

end

app/models/page.rb
class Page < ActiveRecord::Base

  scope :servicios, -> {
    where(layout: 1)
  }

  scope :nosotros, -> {
    where(layout: 2)
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :ejecutivo
  has_many :estado_vehiculos, :dependent => :destroy
  validates_presence_of :placa, :cliente, :marca, :modelo, :anio, :descripcion_del_trabajo, :color, :fecha_ingreso

  enum mail: {
           Guido_Merino: 'merinogu@asegsur.com.ec',
           Juan_Carlos_Pazmino: 'pazminoj@asegsur.com.ec',
           Jose_Paredes: 'paredesj@asegsur.com.ec',
           Jaime_Cevallos: 'cevallosj@asegsur.com.ec',
           Diego_Checa: 'checadie@asegsur.com.ec'
       }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin_layout'

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController

  def new
    @location = "contacto"
    @message = Mensaje.new
  end

  def create
    @message = Mensaje.new(message_params)

    if @message.valid?
      MensajeMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Su mensaje ha sido enviado correctamente."
    else
      flash[:alert] = "Ha ocurrido un error, revise que estén correctos todos los campos."
      render :new
    end
  end

  private

  def message_params
    params.require(:mensaje).permit(:nombre_y_apellidos, :correo, :asunto, :mensaje)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    @page.update_attributes(page_params)
  end

  private
    def page_params
      params.require(:page).permit(:layout, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to :admin_clientes_path
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index

  end

  def servicios
    @page = Page.servicios.first
    @location = "servicios"
  end

  def nosotros
    @page = Page.nosotros.first
    @location = "nosotros"
  end

  def consultar
    if params[:search].present?
      search_param = "#{params[:search]}"
      @cliente = Cliente.where('clientes.identificacion = :search', search: search_param)
    end
    if not @cliente.nil? and @cliente.count > 0
      @vehiculos = @cliente.first.vehiculos
    end

    respond_to do |format|
      format.html {
        @current_nav = 'consultar'
      }
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/validators_helper.rb
module ValidatorsHelper

  class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        record.errors[attribute] << (options[:message] || "no es un correo válido.")
      end
    end
  end

end

app/views/admin/pages/_pages.html.haml
- pages.each do  |page|
  %li.object_list{id: "page_#{page.id}"}
    .ellipsis_100{title: page.title} #{page.title}
    .float-right
      = link_to pages_edit_path(page.id), class: 'edit', remote: true, id: "edit-#{page.id}", title: 'Editar', data: {toggle: 'tooltip'} do
        %i.glyphicon.glyphicon-pencil

app/views/admin/pages/index.html.haml
.row
  .col-md-6
    %h2 Páginas del Sitio

.row
  %section.section
    %ul.list-unstyled#pages_list
      = render 'pages', pages: @pages

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-fixed-top#corporate-nav-bar
  .container
    .navbar-header
      button.navbar-toggle{data-target=".navbar-collapse" data-toggle="collapse" type="button"}
        span.left Menu
        .menu-icon
          span.icon-bar
          span.icon-bar
          span.icon-bar
      a#zp-nav-logo{href="/"}
        .navbar-brand{style="display: block; opacity: 1;"}
          == image_tag 'logo.png'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_admin.html.haml
/ navigation styled for Bootstrap 3.0
%header#corporate-main-nav
  %nav.navbar.navbar-default.navbar#corporate-nav-bar
    .container
      .navbar-header
        %button.navbar-toggle{data: {target: ".navbar-collapse", toggle: "collapse"}, type: "button"}
          %span.left Menu
          .menu-icon
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %a#zp-nav-logo{href: "/"}
          .navbar-brand{style: "display: block; opacity: 1;"}
            %h2
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to 'Dashboard', admin_root_path
          %li
            = link_to 'Clientes', admin_clientes_path
          %li
            = link_to 'Vehículos', admin_vehiculos_path
          %li
            = link_to 'Configurar Estados', admin_estados_path
          %li
            = link_to 'Configurar Ejecutivos', admin_ejecutivos_path
          - if user_signed_in?
            %li
              = link_to 'Salir', destroy_user_session_path, :method=>'delete'
            %li
              = link_to 'Volver al Sitio', root_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Inicio', root_path %></li>
<li><%= link_to 'Servicios', servicios_path %></li>
<li><%= link_to '¿Quiénes Somos?', nosotros_path %></li>
<li><%= link_to 'Contacto', contact_path %></li>
<li><%= link_to 'Consultar mi Vehículo', consultar_path %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Admin', admin_root_path %></li>
  <li><%= link_to 'Salir', destroy_user_session_path, :method=>'delete' %></li>
<% end %>

app/views/layouts/admin_layout.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Administracion Auto Stop LC'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Auto Stop'}"
    == stylesheet_link_tag "admin", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation_admin'
    .container
      main[role="main"]
        == render 'layouts/messages'
        == yield
    footer.marginbottom20
      .container
        hr
        .row
          .col-md-4
            span.copyright &copy; Auto Stop LC 2015
          .col-md-4

    #crud_modal.modal.fade{data-keyboard="false" data-backdrop="static"}
    == yield :extra_modal
== yield :js_footer

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Auto Stop LC'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Auto Stop'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == javascript_include_tag '//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry', 'data-turbolinks-track' => false
    == csrf_meta_tags
  body
    header#corporate-main-nav
      == render 'layouts/navigation'
    main.container[role="main"]
      == render 'layouts/messages'
      == yield
    footer.marginbottom20
      .container
        hr
        .row
          .col-md-4
            span.copyright Copyright &copy; Auto Stop LC 2015
          .col-md-4
            ul.list-inline.social-buttons
              li
                a href="https://twitter.com/AutoStopLC"
                  i.fa.fa-twitter
              li
                a href="https://facebook.com/autostoplc"
                  i.fa.fa-facebook
              li
                a href="https://plus.google.com/+autostoplc"
                  i.fa.fa-google-plus
          .col-md-4
            ul.list-inline.quicklinks
              li
                p Teléfonos
                a href="tel: 022432655"  243-2655
                span &nbsp; - &nbsp;
                a href="tel: 023340669"  604-0992
==yield :js_footer