config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'visitors#index'
  get "servicios", to: "visitors#servicios"
  get "nosotros", to: "visitors#nosotros"
  get "consultar", to: "visitors#consultar"
  post "pages/update"
  get "pages/edit"
  get 'contact', to: 'mensajes#new', as: 'contact'
  post 'contact', to: 'mensajes#create'
  devise_for :users
  resources :users
  namespace :admin do
    root to: 'dashboard#index'
    resources :clientes
    resources :vehiculos
    resources :estados
    resources :pages
    resources :estado_vehiculos
    resources :ejecutivos
  end
end

app/models/adjunto.rb
class Adjunto < ActiveRecord::Base
  belongs_to :estado_vehiculo

  has_attached_file :archivo,
                    :path => ":rails_root/public/adjuntos/:id/:filename",
                    :url  => "/adjuntos/:id/:filename"

  do_not_validate_attachment_file_type :archivo
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/cliente.rb
include ValidatorsHelper

class Cliente < ActiveRecord::Base
  has_many :vehiculos, :dependent => :destroy
  validates_presence_of :identificacion, :nombre_y_apellidos, :tipo_identificacion, :celular, :direccion, :tipo
  validates :correo, presence: true, email: true

  enum tipo: {
           asegurado: 'Asegurado', responsabilidad_civil: 'Responsabilidad Civil', particular: 'Particular'
       }
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nombre,      :validate => true
  attribute :correo,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensaje
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Nuevo Contacto AutoStop",
        :to => "dairon.medina@gmail.org",
        :from => %("#{nombre}" <#{correo}>)
    }
  end
end

app/models/ejecutivo.rb
include ValidatorsHelper

class Ejecutivo < ActiveRecord::Base
  has_many :vehiculos, dependent: :nullify
  validates_presence_of :nombre
  validates :correo, presence: true, email: true
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_many :estado_vehiculos
end

app/models/estado_vehiculo.rb
class EstadoVehiculo < ActiveRecord::Base
  belongs_to :vehiculo
  belongs_to :estado
  has_many :adjuntos, :dependent => :destroy
  validates_presence_of :vehiculo, :estado, :notas,  :fecha_y_hora
end

app/models/mensaje.rb
class Mensaje

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :nombre_y_apellidos, :correo, :asunto, :mensaje

  validates :nombre_y_apellidos,
            presence: true

  validates :correo,
            presence: true
  validates_format_of :correo, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :asunto,
            presence: true

  validates :mensaje,
            presence: true

end

app/models/page.rb
class Page < ActiveRecord::Base

  scope :servicios, -> {
    where(layout: 1)
  }

  scope :nosotros, -> {
    where(layout: 2)
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :ejecutivo
  has_many :estado_vehiculos, :dependent => :destroy
  validates_presence_of :placa, :cliente, :marca, :modelo, :anio, :descripcion_del_trabajo, :color, :fecha_ingreso

  enum mail: {
           Guido_Merino: 'merinogu@asegsur.com.ec',
           Juan_Carlos_Pazmino: 'pazminoj@asegsur.com.ec',
           Jose_Paredes: 'paredesj@asegsur.com.ec',
           Jaime_Cevallos: 'cevallosj@asegsur.com.ec',
           Diego_Checa: 'checadie@asegsur.com.ec'
       }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin_layout'

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController

  def new
    @location = "contacto"
    @message = Mensaje.new
  end

  def create
    @message = Mensaje.new(message_params)

    if @message.valid?
      MensajeMailer.new_message(@message).deliver
      redirect_to contact_path, notice: "Su mensaje ha sido enviado correctamente."
    else
      flash[:alert] = "Ha ocurrido un error, revise que estén correctos todos los campos."
      render :new
    end
  end

  private

  def message_params
    params.require(:mensaje).permit(:nombre_y_apellidos, :correo, :asunto, :mensaje)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    @page.update_attributes(page_params)
  end

  private
    def page_params
      params.require(:page).permit(:layout, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to :admin_clientes_path
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index

  end

  def servicios
    @page = Page.servicios.first
    @location = "servicios"
  end

  def nosotros
    @page = Page.nosotros.first
    @location = "nosotros"
  end

  def consultar
    if params[:search].present?
      search_param = "#{params[:search]}"
      @cliente = Cliente.where('clientes.identificacion = :search', search: search_param)
    end
    if not @cliente.nil? and @cliente.count > 0
      @vehiculos = @cliente.first.vehiculos
    end

    respond_to do |format|
      format.html {
        @current_nav = 'consultar'
      }
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/validators_helper.rb
module ValidatorsHelper

  class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        record.errors[attribute] << (options[:message] || "no es un correo válido.")
      end
    end
  end

end

app/views/visitors/_page.html.erb
<% if current_user.nil? %>
    <%= raw @page.content %>
<% else %>
    <%= form_tag pages_update_path, remote: true do %>

        <%= hidden_field_tag :id, @page.id %>
        <%= cktext_area_tag "page[content]", @page.content, ckeditor: {toolbar: "mini"} %>

        <%= submit_tag "Guardar Contenido", disable_with: "Guardando...", class: "btn" %>

    <% end %>
<% end %>

app/views/visitors/_vehicle_status.html.haml
- if @cliente && @cliente.count.zero?
  .alert.alert-danger{role: 'alert'}
    %span.glyphicon.glyphicon-exclamation-sign{aria: {hidden: "true"}}
    %span.sr-only
      Información:
    Usted no tiene ningún vehículo en nuestro taller o ha introducido mal sus datos.
    Por favor ingrese correctamente su identificación.
- else
  - if @vehiculos.count > 0
    - @vehiculos.each do |v|
      .panel-group#acordion
        .panel.panel-default
          .panel-heading
            %h4.panel-title.row
              %span.col-sm-4
                #{v.marca} #{v.modelo}
                %b.label.label-danger
                  #{v.placa}
              %span.col-sm-6
                - if v.estado_vehiculos.count > 0
                  %b
                    Estado Actual:
                  #{v.estado_vehiculos.all.last.estado.nombre or '-'}
              %span.col-sm-2
                %button.btn.btn-sm.btn-default{data: {toggle: 'collapse', target: "#vehiculo_#{v.id}"}}
                  %span.glyphicon.glyphicon-collapse-down
                  Ver Detalles
          .panel-collapse.collapse{id: "vehiculo_#{v.id}"}
            .panel-body
              %b
                Fecha Ingreso al Taller:
              #{v.fecha_ingreso or '-'}
              %br/
              - if v.estado_vehiculos.count > 0
                %b Estado de su Vehículo:
                #{v.estado_vehiculos.all.last.estado.nombre or '-'}
                %br/
                %p
                  %b
                    Fecha de Actualización:
                  #{v.estado_vehiculos.all.last.fecha_y_hora or '-'}
                %p
                  %b
                    Detalles:
                  #{v.estado_vehiculos.all.last.notas or '-'}
                - if not v.estado_vehiculos.all.last.adjuntos.nil?
                  %p
                    %b
                      Archivos Adjuntos:
                      - v.estado_vehiculos.all.last.adjuntos.each do |f|
                        = link_to f.archivo.url do
                          .image{id: "photo-#{f.id}"}
                            = image_tag f.archivo.url, class: 'img-thumbnail img-responsive img-rounded', alt: f.archivo_file_name, style: 'width: 200px;'

app/views/visitors/consultar.html.haml
.row
  .col-md-6.col-md-offset-3
    %span
      = form_tag consultar_path, remote: true, method: :get do
        .form-group
          %p
            Ingrese su número de identificación(Cédula, RUC o Pasaporte) para consultar el estado de su vehículo.
          .input-group
            = text_field_tag :search, '', placeholder: 'Consultar estado de mi vehículo...', class: 'form-control', aria:{describedby:"search_button"}
            %span#search_button.input-group-addon{style: 'padding: 0 3px;'}
              = button_tag class: 'btn btn-red', data: { disable_with: 'Buscando...'} do
                %i.glyphicon.glyphicon-search.col-md-6

.row
  .col-sm-8.col-sm-offset-2#status_content

app/views/visitors/index.html.slim
.row.nomargin
  .col-sm-8
    #home-slider.carousel.slide data-ride="carousel"
      ol.carousel-indicators
        li.active data-slide-to="0" data-target="#home-slider"
        li data-slide-to="1" data-target="#home-slider"
        li data-slide-to="2" data-target="#home-slider"
      .carousel-inner role="listbox"
        .item.active
          == image_tag 'slide1.png'
        .item
          == image_tag 'slide2.png'
        .item
          == image_tag 'slide3.png'

  .col-sm-4.text-center
    br
    .text
      strong Tu vehículo
    .text en manos de los
    .text
      strong Mejores
    .text Profesionales
    br
    = link_to "Cotizar Ahora", contact_path, class: 'btn btn-siteland'
.row.margintop20
  .col-sm-3.bucket
    == image_tag 'repair_services.jpg'
    == link_to "Servicios", servicios_path
  .col-sm-3.bucket
    == image_tag 'happy_customer.jpg'
    == link_to "Experiencia", nosotros_path
  .col-sm-3.bucket
    == image_tag 'location.jpg'
    == link_to "Ubicación", contact_path
  .col-sm-3.bucket
    == image_tag 'contact_us.jpg'
    == link_to "Contacto", contact_path
.row.marginbottom20.margintop20.text-center
  .col-sm-6.col-sm-offset-3
    h3 Trabajamos con las principales aseguradoras del Ecuador
    hr

app/views/visitors/nosotros.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-hader">
      <h1>¿Quiénes Somos?</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= render 'page' %>
  </div>
</div>

app/views/visitors/servicios.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-hader">
      <h1>Servicios</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= render 'page' %>
  </div>
</div>