config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'visitors#index'
  get "servicios", to: "visitors#servicios"
  get "nosotros", to: "visitors#nosotros"
  get "consultar", to: "visitors#consultar"
  post "pages/update"
  get "pages/edit"
  get 'contact', to: 'mensajes#new', as: 'contact'
  post 'contact', to: 'mensajes#create'
  devise_for :users
  resources :users
  namespace :admin do
    root to: 'dashboard#index'
    resources :clientes
    resources :vehiculos
    resources :estados
    resources :pages
    resources :estado_vehiculos
    resources :ejecutivos
  end
end

app/models/cliente.rb
include ValidatorsHelper

class Cliente < ActiveRecord::Base
  has_many :vehiculos, :dependent => :destroy
  validates_presence_of :identificacion, :nombre_y_apellidos, :tipo_identificacion, :celular, :direccion, :tipo
  validates :correo, presence: true, email: true

  enum tipo: {
           asegurado: 'Asegurado', responsabilidad_civil: 'Responsabilidad Civil', particular: 'Particular'
       }
end

app/controllers/admin/clientes_controller.rb
class Admin::ClientesController < AdminController
  def index
    @entities = Cliente
    if params[:search].present?
      search_param = "%#{params[:search]}%"
      @entities =
          @entities.where('clientes.nombre_y_apellidos like :search or clientes.identificacion like :search', search: search_param)
    end
    @entities = @entities.paginate(page: params[:page])
    respond_to do |format|
      format.html {
        @current_nav = 'Clientes'
      }
      format.js {}
    end
  end

  def show
    @entity = Cliente.find(params[:id])
  end

  def new
    @from_autocomplete = 'true'.eql? params[:from_autocomplete]
    @autocomplete_id = params[:autocomplete_id]
    @entity = Cliente.new()
  end

  def create
    @entities = Cliente.paginate(page: params[:page])
    @from_autocomplete = 'true'.eql? params[:from_autocomplete]
    @autocomplete_id = params[:autocomplete_id]
    @entity = Cliente.create(entity_params)
  end

  def edit
    @entity = Cliente.find(params[:id])
  end

  def update
    @entities = Cliente.paginate(page: params[:page])
    @entity = Cliente.find(params[:id])
    @entity.update_attributes(entity_params)
    render :create
  end

  def destroy
    @entity = Cliente.find(params[:id])
    render js: 'alert("Could not delete entity");' unless @entity.destroy
  end

=begin
  def autocomplete
    entities =
        @company
            .entities
            .joins("left outer join property_entities on entities.id = property_entities.entity_id and property_entities.property_id = #{params[:pid]}")
            .where("entities.company_name LIKE :search or entities.contact_name LIKE :search or entities.contact_last_name LIKE :search", search: "%#{params[:term]}%")
            .select("entities.id, entities.company_name, entities.contact_name, entities.contact_last_name, entities.phone, property_entities.account_number")
            .uniq

    result = entities.collect do |e|
      {id: e.id, value: e.display_name, contact: e.contact_name + ' ' + e.contact_last_name, phone: e.phone, company_name: e.company_name, account: e.account_number}
    end
    render json: result
  end
=end

  private

  def entity_params
    params.require(:cliente).permit(:nombre_y_apellidos, :empresa, :tipo_identificacion, :identificacion, :direccion, :correo, :telefono, :celular, :tipo)
  end
end

app/views/admin/clientes/_edit.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      %button.close{type:"button", data:{dismiss:"modal"}, aria:{label:"Close"}}
        %span{aria:{hidden:"true"}} &times;
      %h3 Editar Cliente: "#{@entity.identificacion}"
    = render 'form'

app/views/admin/clientes/_form.html.haml
= form_for [:admin, @entity], remote: true do |f|
  = hidden_field_tag :from_autocomplete, @from_autocomplete
  = hidden_field_tag :autocomplete_id, @autocomplete_id
  .modal-body
    .alert.alert-block.alert-danger.alert-dismissable.error_box{style: "display:none;"}
      %a.close{data: {'dismiss': 'alert'}} &times;
      %ul.list-unstyled.errors
    .row
      .col-md-6
        .row
          .col-md-6
            .form-group
              = f.label :nombre_y_apellidos, class: 'control-label'
              = f.text_field :nombre_y_apellidos, class: 'form-control'
          .col-md-6
            .form-group
              = f.label :empresa, class: 'control-label'
              = f.text_field :empresa, class: 'form-control'
        .row
          .col-md-6
            .form-group
              = f.label :tipo_identificacion, class: 'control-label'
              = f.select :tipo_identificacion,options_for_select([['Cedula', '0'], ['RUC', '1'], ['Pasaporte', '2']], selected: '0'),{}, {class: 'form-control'}
          .col-md-6
            .form-group
              = f.label :identificacion, class: 'control-label'
              = f.text_field :identificacion, class: 'form-control'
        .row
          .col-md-6
            = f.label :tipo, class: 'control-label'
            = f.select :tipo, options_for_select(Cliente.tipos, selected: 'asegurado'),{}, {class: 'form-control'}
        .row
          .col-md-12
            .form-group
              = f.label :direccion, class: 'control-label'
              = f.text_area :direccion, class: 'form-control'
      .col-md-6
        .col-md-12
          .form-group
            = f.label :correo, class: 'control-label'
            = f.text_field :correo, class: 'form-control'
        .col-md-4
          .form-group
            = f.label :telefono, class: 'control-label'
            = f.text_field :telefono, class: 'form-control'
        .col-md-4
          .form-group
            = f.label :celular, class: 'control-label'
            = f.text_field :celular, class: 'form-control'
  .modal-footer
    = link_to "Cancelar", '#', class: 'btn', data: {dismiss: 'modal'}
    = button_tag class: 'btn btn-red' do
      %i.glyphicon.glyphicon.glyphicon-floppy-disk
      Guardar

app/views/admin/clientes/_list.html.haml
- @entities.each do |entity|
  %tr{id: "entity_#{entity.id}"}
    %td
      %b
        - unless entity.empresa.empty?
          #{entity.empresa}
          %br/
          Persona de Contacto:
      #{entity.nombre_y_apellidos}
    %td #{entity.tipo.humanize}
    %td #{entity.identificacion}
    %td
      #{entity.correo}
    %td
      %b Convencional:
      #{entity.telefono or '-'}
      %br/
      %b Celular:
      #{entity.celular or '-'}
    %td.text-center
      .badge
        #{entity.vehiculos.count}
    %td.text-center
      = link_to edit_admin_cliente_path(entity.id), remote: true, class: 'btn btn-primary btn-sm', title: 'Editar', data: {toggle: 'tooltip'} do
        %i.glyphicon.glyphicon-pencil
      = link_to admin_cliente_path(entity.id), method: :delete, remote: true, class: 'btn btn-default btn-sm delete', title: 'Eliminar', data: {toggle: 'tooltip', confirm: "¿Seguro que desea eliminar este cliente. Tiene  #{entity.vehiculos.count} vehículos?"} do
        %i.glyphicon.glyphicon-trash
      = link_to new_admin_vehiculo_path(client: entity.id), remote: true, class: 'btn btn-red btn-sm', title: 'Ingresar Vehiculo', data: {toggle: 'tooltip'} do
        %i.glyphicon.glyphicon-plus
        Ingresar Vehiculo

app/views/admin/clientes/_new.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      %button.close{type:"button", data:{dismiss:"modal"}, aria:{label:"Close"}}
        %span{aria:{hidden:"true"}} &times;
      %h3 Ingresar Cliente
    = render 'form'

app/views/admin/clientes/index.html.haml
.row
  .col-md-6
    %span
      = form_tag admin_clientes_path, remote: true, method: :get do
        .form-group
          %p
            Puedes buscar: nombre y apellidos: ej. Pedro Chicaiza, cédula: ej. 1716976384
          .input-group
            = text_field_tag :search, '', placeholder: 'Buscar', class: 'form-control', aria:{describedby:"search_button"}
            %span#search_button.input-group-addon{style: 'padding: 0 3px;'}
              = button_tag class: 'btn btn-red', data: { disable_with: 'Buscando...'} do
                %i.glyphicon.glyphicon-search.col-md-6
  .pull-right
    = link_to new_admin_cliente_path, remote: true, class: 'btn btn-red' do
      %i.glyphicon.glyphicon-plus-sign
      Agregar Cliente

.row
  .col-md-12
    %table.table.table-condensed.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Cliente(Persona y/o Empresa)
          %th Tipo Cliente
          %th Identificación
          %th Correo
          %th Teléfonos
          %th.text-center Vehículos Ingresados
          %th.text-center{style: 'width: 90px;'} Acciones
      %tbody#entities_content
        = render 'list'