config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'visitors#index'
  get "servicios", to: "visitors#servicios"
  get "nosotros", to: "visitors#nosotros"
  get "consultar", to: "visitors#consultar"
  post "pages/update"
  get "pages/edit"
  get 'contact', to: 'mensajes#new', as: 'contact'
  post 'contact', to: 'mensajes#create'
  devise_for :users
  resources :users
  namespace :admin do
    root to: 'dashboard#index'
    resources :clientes
    resources :vehiculos
    resources :estados
    resources :pages
    resources :estado_vehiculos
    resources :ejecutivos
  end
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :ejecutivo
  has_many :estado_vehiculos, :dependent => :destroy
  validates_presence_of :placa, :cliente, :marca, :modelo, :anio, :descripcion_del_trabajo, :color, :fecha_ingreso

  enum mail: {
           Guido_Merino: 'merinogu@asegsur.com.ec',
           Juan_Carlos_Pazmino: 'pazminoj@asegsur.com.ec',
           Jose_Paredes: 'paredesj@asegsur.com.ec',
           Jaime_Cevallos: 'cevallosj@asegsur.com.ec',
           Diego_Checa: 'checadie@asegsur.com.ec'
       }
end

app/controllers/admin/vehiculos_controller.rb
class Admin::VehiculosController < AdminController
  def index
    @vehiculos = Vehiculo
    if params[:search].present?
      search_param = "%#{params[:search]}%"
      @vehiculos =
          @vehiculos.where('vehiculos.placa like :search or vehiculos.modelo like :search', search: search_param)
    end
    @vehiculos = @vehiculos.paginate(page: params[:page])
    respond_to do |format|
      format.html {
        @current_nav = 'Vehiculos'
      }
      format.js {}
    end
  end

  def show
    @vehiculo = Vehiculo.find(params[:id])
    @statuses = @vehiculo.estado_vehiculos.reorder('fecha_y_hora desc')
  end

  def new
    if params[:client].present?
      @cliente = Cliente.find(params[:client])
    end
    @vehiculo = Vehiculo.new()
    @vehiculo.fecha_ingreso = Date.current
  end

  def create
    @vehiculos = Vehiculo.paginate(page: params[:page])
    @vehiculo = Vehiculo.create(vehicle_params)
  end

  def edit
    @vehiculo = Vehiculo.find(params[:id])
  end

  def update
    @vehiculos = Vehiculo.paginate(page: params[:page])
    @vehiculo = Vehiculo.find(params[:id])
    @vehiculo.update_attributes(vehicle_params)
    render :create
  end

  def destroy
    @vehiculo = Vehiculo.find(params[:id])
    render js: 'alert("No se puede borrar este Vehículo");' unless @vehiculo.destroy
  end

  private

  def vehicle_params
    params.require(:vehiculo).permit(:cliente_id, :placa, :marca, :modelo, :anio, :color, :responsabilidad_civil, :aseguradora, :poliza, :kilometraje_actual, :descripcion_del_trabajo, :fecha_ingreso, :ejecutivo_id)
  end
end

app/views/admin/vehiculos/_edit.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      %button.close{type:"button", data:{dismiss:"modal"}, aria:{label:"Close"}}
        %span{aria:{hidden:"true"}} &times;
      %h3 Editar Vehículo: "#{@vehiculo.placa}"
    = render 'form'

app/views/admin/vehiculos/_form.html.haml
= form_for [:admin, @vehiculo], remote: true do |f|
  = hidden_field_tag :from_autocomplete, @from_autocomplete
  = hidden_field_tag :autocomplete_id, @autocomplete_id
  .modal-body
    .alert.alert-block.alert-danger.alert-dismissable.error_box{style: "display:none;"}
      %a.close{data: {'dismiss': 'alert'}} &times;
      %ul.list-unstyled.errors
    - if @cliente.nil?
      .row
        .col-md-12
          .form-group
            = f.label :cliente_id, class: 'control-label'
            = f.select :cliente_id, Cliente.all.collect{ |g| [g.nombre_y_apellidos, g.id] }, { include_blank: true }, { class: 'form-control' }
          %hr
    - unless @cliente.nil?
      = f.hidden_field :cliente_id, value: @cliente.id
    .row
      .col-md-6
        %h4 Datos del Auto:
        %hr
        .row
          .col-md-6
            .form-group
              = f.label :placa, class: 'control-label'
              = f.text_field :placa, class: 'form-control'
          .col-md-6
            .form-group
              = f.label :fecha_ingreso, class: 'control-label'
              .input-group.date#datetimepicker1
                = f.text_field :fecha_ingreso, class: 'form-control', value: @vehiculo.fecha_ingreso.strftime("%d/%m/%Y"), data: {format: "dd/MM/yyyy" }
                %span.input-group-addon
                  %i.glyphicon.glyphicon-calendar
        .row
          .col-md-6
            .form-group
              = f.label :marca, class: 'control-label'
              = f.text_field :marca, class: 'form-control'
          .col-md-6
            .form-group
              = f.label :modelo, class: 'control-label'
              = f.text_field :modelo, class: 'form-control'
        .row
          .col-md-6
            .form-group
              = f.label :anio, class: 'control-label'
              = f.text_field :anio, class: 'form-control'
          .col-md-6
            .form-group
              = f.label :color, class: 'control-label'
              = f.text_field :color, class: 'form-control'
      .col-md-6
        .col-md-12
          %h4 Datos para el Trabajo:
          %hr
          .form-group
            = f.label :responsabilidad_civil, class: 'control-label'
            = f.text_field :responsabilidad_civil, class: 'form-control'
        .col-md-12
          .form-group
            = f.label :ejecutivo_id, class: 'control-label'
            = f.select :ejecutivo_id, options_for_select(Ejecutivo.order("nombre").map { |e| [e.nombre + "( #{e.correo} )", e.id] }, selected: @vehiculo.ejecutivo_id),{include_blank: true}, {class: 'form-control'}
        .col-md-12
          .form-group
            = f.label :aseguradora, class: 'control-label'
            = f.text_field :aseguradora, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :poliza, class: 'control-label'
            = f.text_field :poliza, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :kilometraje_actual, class: 'control-label'
            = f.text_field :kilometraje_actual, class: 'form-control'
    .row
      .col-md-12
        .row
          .col-md-12
            .form-group
              = f.label :descripcion_del_trabajo, class: 'control-label'
              = f.text_area :descripcion_del_trabajo, class: 'form-control'
  .modal-footer
    = link_to "Cancelar", '#', class: 'btn', data: {dismiss: 'modal'}
    = button_tag class: 'btn btn-red' do
      %i.glyphicon.glyphicon-floppy-disk
      Guardar

:javascript
  $("#datetimepicker1").datetimepicker({
    format: "DD/MM/YYYY",
    locale: "es",
  });

app/views/admin/vehiculos/_list.html.haml
- @vehiculos.each do |vehiculo|
  %tr{id: "vehiculo_#{vehiculo.id}"}
    %td
      %b
        - unless vehiculo.cliente.empresa.empty?
          #{vehiculo.cliente.empresa}
          %br/
          Persona de Contacto:
      #{vehiculo.cliente.nombre_y_apellidos}
    %td #{vehiculo.placa}
    %td
      #{vehiculo.marca}
    %td
      #{vehiculo.modelo or '-'}
    %td
      #{vehiculo.fecha_ingreso or '-'}
    %td
      #{vehiculo.responsabilidad_civil or '-'}
    %td
      #{vehiculo.aseguradora or 'Ninguna'}
    %td.text-center
      - if vehiculo.estado_vehiculos.count > 0
        %span.label.label-danger
          #{vehiculo.estado_vehiculos.all.last.estado.nombre or '-'}
    %td.text-center
      = link_to edit_admin_vehiculo_path(vehiculo.id), remote: true, class: 'btn btn-primary btn-sm', title: 'Editar', data: {toggle: 'tooltip'} do
        %i.glyphicon.glyphicon-pencil
      = link_to admin_vehiculo_path(vehiculo.id), method: :delete, remote: true, class: 'btn btn-default btn-sm delete', title: 'Eliminar', data: {toggle: 'tooltip', confirm: '¿Seguro que desea eliminar este vehículo?'} do
        %i.glyphicon.glyphicon-trash
    %td.text-center
      .input-group-btn
        %button.btn.btn-default.btn-block.dropdown-toggle{aria:{expanded: "false"}, data: {toggle: "dropdown"}, type: "button"}
          Cambiar Estado
          %span.caret
        %ul.dropdown-menu.noclose{role: 'menu'}
          - Estado.all.each do |estado|
            %li.checkbox-container
              = link_to estado.nombre, new_admin_estado_vehiculo_path(vehiculo: vehiculo.id, estado: estado.id), remote: true
      -#= link_to edit_admin_cliente_path(vehiculo.id), remote: true, class: 'btn btn-default btn-block', title: 'Ingresar Vehiculo', data: {toggle: 'tooltip'} do
      -#  %i.glyphicon.glyphicon-align-center
      -#  Historial Estados

app/views/admin/vehiculos/_new.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      %button.close{type:"button", data:{dismiss:"modal"}, aria:{label:"Close"}}
        %span{aria:{hidden:"true"}} &times;
      %h3 Ingresar Vehículo al Taller
    = render 'form'

app/views/admin/vehiculos/_show.html.haml
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      %button.close{type:"button", data:{dismiss:"modal"}, aria:{label:"Close"}}
        %span{aria:{hidden:"true"}} &times;
      %h3
        Historial del vehículo:
        #{@vehiculo.placa}
    .modal-body{id: "historial_id_#{@vehiculo.id}"}
      %table
        %thead
          %tr
            %th.col-md-7
              Given Error
            %th.col-md-2
              Row
            %th.col-md-3
              Time
        %tbody
          - @upload.import_errors.reorder('created_at desc').each do |error|
            %tr
              %td.col-md-7
                #{error.error_description}
              %td.col-md-2
                #{error.row}
              %td.col-md-3
                #{error.created_at.strftime('%I:%M:%S %p')}

app/views/admin/vehiculos/index.html.haml
.row
  .col-md-6
    %span
      = form_tag admin_vehiculos_path, remote: true, method: :get do
        .form-group
          %p
            Puedes buscar: placa: ej. XBB2396, marca: ej. chevrolet
          .input-group
            = text_field_tag :search, '', placeholder: 'Buscar', class: 'form-control', aria:{describedby:"search_button"}
            %span#search_button.input-group-addon{style: 'padding: 0 3px;'}
              = button_tag class: 'btn btn-red', data: { disable_with: 'Buscando...'} do
                %i.glyphicon.glyphicon-search.col-md-6
  .pull-right
    - unless Cliente.all.count.zero?
      = link_to new_admin_vehiculo_path, remote: true, class: 'btn btn-red' do
        %i.glyphicon.glyphicon-plus-sign
        Ingresar Vehículo

.row
  .col-md-12
    %table.table.table-condensed.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Cliente(Persona y/o Empresa)
          %th Placa
          %th Marca
          %th Modelo
          %th Fecha Ingreso
          %th Responsabilidad Civil
          %th Aseguradora
          %th Estado Actual
          %th.text-center{style: 'width: 90px;'} Acciones
          %th.text-center{style: 'width: 130px;'} Acciones
      %tbody#vehicles_content
        = render 'list'